### ISSUE TITLE
[WIP] 添加在 Hook 资源时获取宿主原始资源的扩展功能

### ISSUE THREAD

**Issue by buffcow** [HighCapable/YukiHookAPI#36]
框架中貌似没有封装获取app资源的方法
例如我要获取app的string，要经过以下步骤：

```kotlin
val id = appResources!!.getIdentifier(
                    "example_name",
                    "string",
                    packageName
                )
appResources.getString(id)
```

这样略显麻烦，有什么优雅的方法可以代替吗

**Comment by fankes** [comment]
你可以在宿主的资源或上下文扩展方法中调用 `injectModuleAppResources` 把模块的资源注入宿主，然后用宿主的资源直接获取。
这个方法不是必须的扩展，不会被添加。

**Comment by yangyiyu08** [comment]
> 你可以在宿主的资源或上下文扩展方法中调用 `injectModuleAppResources` 把模块的资源注入宿主，然后用宿主的资源直接获取。 这个方法不是必须的扩展，不会被添加。 参考文档→[这里](https://fankes.github.io/YukiHookAPI/zh-cn/api/special-features/host-inject.html#%E6%B3%A8%E5%85%A5%E6%A8%A1%E5%9D%97%E8%B5%84%E6%BA%90-resources)

我不是想获取模块的资源，而是获取**被hook的宿主**的res资源噢

**Comment by yangyiyu08** [comment]
就比方说，我有个这样的需求：
hook app 的 res，将 string 为 example_name 的值加上ab

目前的代码是这样的:
```kotlin
            injectResource {
                conditions {
                    name = "example_name"
                    string()
                }
                // 获取原有的值
                val id = appResources!!.getIdentifier(
                    "example_name",
                    "string",
                    packageName
                )
                // 加上 ab
                replaceTo(appResources!!.getString(id) + "ab")
            }
```

**Comment by fankes** [comment]
这样啊，后面可以加一个扩展

**Comment by yangyiyu08** [comment]
ok, 也可以考虑一下不在hook 资源的情况下,也可以快捷的 根据资源名称获取 app 资源的值😀

**Comment by fankes** [comment]
> ok, 也可以考虑一下不在hook 资源的情况下,也可以快捷的 根据资源名称获取 app 资源的值😀

这属于额外扩展了，可以加上

**Comment by yangyiyu08** [comment]
> > ok, 也可以考虑一下不在hook 资源的情况下,也可以快捷的 根据资源名称获取 app 资源的值😀
> 
> 这属于额外扩展了，可以加上

好的 辛苦了👍

**Comment by fankes** [comment]
```kotlin
injectResource {
    conditions {
        name = "example_name"
        string()
    }
    // 加上 ab
    replaceTo { "${it}ab" }
}
```

根据你的需求，这个方法增加的扩展为在回调中可以拿到 `it` 并在最后一位返回需要修改的内容。

**Comment by buffcow** [comment]
nice

**Comment by fankes** [comment]
`1.2.0` 版本已发布，该功能已添加。
