### ISSUE TITLE
YukiHookPrefsBridge read value not working in the release mode

### ISSUE THREAD

**Issue by TheVigor** [HighCapable/YukiHookAPI#52]
My module implements the logic of saving some parameters to disk using YukiHookPrefsBridge. When the method hook I need is called, I read the stored value using YukiHookPrefsBridge and substitute it as the return value. The problem is that in the debug build everything works, but as soon as I switch to the release, reading the value stops working and starts returning to the default value specified in the shared preferences. I can’t figure out what the problem is, maybe I need to specify some additional rules for obfuscation (I use R8 in the release build)?

**Comment by fankes** [comment]
You need tell me your hook framework / environment that using by the xposed  module like LSPosed x.x.x Android x.x

**Comment by fankes** [comment]
The xsp have fixed on LSPosed 1.9
2

**Comment by TheVigor** [comment]
Vendor: Samsung Galaxy A04E
Android Version: Android 12 (One UI 4.1)
LSPosed Version: 1.8.6
Yuki Version: 1.1.11

Thanks, I'll try to update LSPosed. Maybe there is something else that needs to be checked?

**Comment by fankes** [comment]
Xsp sometimes not working and not working for all devices, there will be a new storage solutions later and with libxposed using LSPosed’s remote storage solution on `2.0.0` version.

We can't solve this problem.
