### ISSUE TITLE
Classifier 'enum class HookEntryType : Enum<HookEntryType>' does not have a companion object

### ISSUE THREAD

**Issue by lightsummer233** [HighCapable/YukiHookAPI#65]
![image](https://github.com/HighCapable/YukiHookAPI/assets/93428659/e9ecde90-f02c-41ca-a412-37a437dfe279)

HookEntry_Impl.kt:47:35 Classifier 'enum class HookEntryType : Enum<HookEntryType>' does not have a companion object, so it cannot be used as an expression.

请问这个如何解决？或者需要我提供其他信息吗？

**Comment by fankes** [comment]
这是 kc 的问题，更新你的 as 版本或 gradle 使用的 jdk 版本

**Comment by lightsummer233** [comment]
![image](https://github.com/HighCapable/YukiHookAPI/assets/93428659/5e790a70-e0b2-4c24-82fd-7220567bac5b)
![image](https://github.com/HighCapable/YukiHookAPI/assets/93428659/3c630832-cb67-4719-8311-be68d856a2b0)
![image](https://github.com/HighCapable/YukiHookAPI/assets/93428659/954b4abc-e31e-4a27-97ce-23d11e21aa7e)
考虑教教怎么解决吗）

**Comment by lightsummer233** [comment]
没事了，Kotlin 降级回 1.9.22 就行了）

**Comment by fankes** [comment]
你不会用的 rc 吧，目前的最新版本就是 1.9.22

**Comment by lightsummer233** [comment]
> 你不会用的 rc 吧，目前的最新版本就是 1.9.22

用的 2.0.0-Beta3（

**Comment by fankes** [comment]
> > 你不会用的 rc 吧，目前的最新版本就是 1.9.22
> 
> 用的 2.0.0-Beta3（

那你 [ksp 版本](https://github.com/google/ksp/releases/tag/2.0.0-Beta3-1.0.17) 也要保持一致，如果还是不行那就等稳定版再看

**Comment by lightsummer233** [comment]
> > > 你不会用的 rc 吧，目前的最新版本就是 1.9.22
> > 
> > 用的 2.0.0-Beta3（
> 
> 那你 [ksp 版本](https://github.com/google/ksp/releases/tag/2.0.0-Beta3-1.0.17) 也要保持一致，如果还是不行那就等稳定版再看

我最开始提 issue 的时候就是一致的）
等正式版再说吧）
