### ISSUE TITLE
registerModuleAppActivities() 注册活动，不会初始化activity

### ISSUE THREAD

**Issue by StarYuhen** [HighCapable/YukiHookAPI#66]
能够跳转到设定的proxyClassName值，但是ModuleAppActivity继承的类，onCreate等函数并不会被创建。

```kt
 onAppLifecycle {
                attachBaseContext { baseContext, hasCalledSuper ->
                    if (hasCalledSuper) run {
                        appClassLoader = baseContext.classLoader

                        // YLog.warn("HookEntry attachBaseContext success")
                    }
                }
                onCreate {
                    // 注入模块资源
                    injectModuleAppResources()
                    // 注册模块activity
                   registerModuleAppActivities()
}
```
而注册的activiy代码为：
```kt
class HOOKActivity : ModuleAppActivity(){
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        YLog.info("HOOKActivity onCreate")
}
}
```
intent进入活动使用的是：
```kt
val intent=Intent(context, HOOKActivity::class.java).apply {
        addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
    }

   context.startActivity(intent)
    YLog.info("intent：$intent")
```
能够打印intent的值，并且能根据设定的proxyClassName进入到宿主app的指定活动，但初始化代码并不会完成。
可能是因为使用
```kt
        YukiXposedEvent.events {
            onHandleLoadPackage {
                XposedHelpers.findAndHookMethod(className.toClass(),
                    methodName,
                    object : XC_MethodHook() {
                        override fun afterHookedMethod(param: MethodHookParam?) {
```
来获取context的方法，用yuki框架自带的挂载不上，少部分函数能挂载，但无法获取context和其他值。

**Comment by fankes** [comment]
这个功能是实验性的，所以可能无法在所有应用中工作，一些应用有反 Hook 功能，可能无法注入 Instrument，所以这是导致可能会失败的原因，如果你想获取一个存在的  `context` 你可以使用 `systemContext` 并直接开始 Hook，请记住 `onAppLifecycle` 并不是每次都能注入成功。
另外请把你的文字排版调整一下，提供最小复现 demo 链接和被 Hook 的宿主。

**Comment by StarYuhen** [comment]
> 这个功能是实验性的，所以可能无法在所有应用程序中工作，一些应用程序有反Hook功能，可能无法注入仪器，所以这导致可能会失败的原因，如果你想获取一个存在的你可以使用 `context`并`systemContext`直接开始 Hook，请记住`onAppLifecycle`不要每次注入成功。 另外请把你的文字排版调整一下，提供最小复现演示链接并被 Hook 的动作。

文本排版调整好了，复现代码和hook的方法，等到明天发zip给你

**Comment by fankes** [comment]
好的

**Comment by StarYuhen** [comment]
> 好的

但有一些疑惑点，根据hook的反应，registerModuleAppActivities是已经将我所写的activity注入进去了的，Resources也是注入了的，为什么onCreate函数并未初始化，hook的反应也是正常跳转接替的宿主app的活动，模块的没有将其覆盖。

yuki框架的简易方法，如....toclass()....hook().after{},这样在部分反hook的app上能找到挂载点，但是无法注入hook的after之类的代码。
但一旦使用YukiXposedEvent.events 的原生onHandleLoadPackage，是能够正常使用的。

请问像这种情况，一般是什么问题导致的

**Comment by StarYuhen** [comment]
经过几天的学习和实战，大部分问题已经绕过解决了，唯有挂载activity失败，可能是也是经验问题，因此关闭

**Comment by fankes** [comment]
好吧，有问题随时联系
