### ISSUE TITLE
两个小建议

### ISSUE THREAD

**Issue by 3508454055** [HighCapable/YukiHookAPI#72]
1，开启“始终在状态栏中显示时间”之后，锁屏的时候，状态栏不显示时间
2，希望增加锁屏时钟显示秒数
![Screenshot_2024-04-26-09-22-05-756_lockscreen-edit](https://github.com/HighCapable/YukiHookAPI/assets/74099298/2613c149-1a08-4564-8eb9-98a81293069d)

**Comment by fankes** [comment]
你是否来错仓库了
