### ISSUE TITLE
Kotlin 2.0 Support for Public Release

### ISSUE THREAD

**Issue by Art-Chen** [HighCapable/YukiHookAPI#78]
考虑发个源码最新支持Kotlin 2.0的版本到Maven吗，Pre-Release也行

**Comment by pomelohan** [comment]
同求

**Comment by fankes** [comment]
最近真的很忙，没时间，先用 maven local 吧

**Comment by DreamMoonCai** [comment]
可以先试试[KYukiHookAPI](https://github.com/DreamMoonCai/KYukiHookAPI)

仓库:mavenCentral()
引用:implementation("io.github.dreammooncai.yukihookapi:api-kotlin:1.0.1")
引用反射:implementation("io.github.dreammooncai.yukireflection:api-kotlin:1.0.1")
KYukiHookAPI与原YukiHookAPI是不允许共存的(因为原来的还没有在仓库发布支持Kotlin2.0的版本，KYuki基于2.0制作所以配套了2.0版本的原Yuki)
KYukiHookAPI中包含YukiHookAPI同时包含YukiReflection，所以不需要额外引用，但是并不直接包括其KYuki反射部分，需要KYuki的反射部分需要额外引用KYukiReflection，KYukiHook对原YukiHook增加了对Kotlin相关反射对象的快捷Hook拓展，文档暂时没有更新，可以先参考代码里的注释使用

**Comment by fankes** [comment]
> 可以先试试[KYukiHookAPI](https://github.com/DreamMoonCai/KYukiHookAPI)
> 
> 
> 
> 仓库:mavenCentral()
> 
> 引用:implementation("io.github.dreammooncai.yukihookapi:api-kotlin:1.0.1")
> 
> 引用反射:implementation("io.github.dreammooncai.yukireflection:api-kotlin:1.0.1")
> 
> KYukiHookAPI与原YukiHookAPI是不允许共存的(因为原来的还没有在仓库发布支持Kotlin2.0的版本，KYuki基于2.0制作所以配套了2.0版本的原Yuki)
> 
> KYukiHookAPI中包含YukiHookAPI同时包含YukiReflection，所以不需要额外引用，但是并不直接包括其KYuki反射部分，需要KYuki的反射部分需要额外引用KYukiReflection，KYukiHook对原YukiHook增加了对Kotlin相关反射对象的快捷Hook拓展，文档暂时没有更新，可以先参考代码里的注释使用

别整你的 kyuki 了，你 pr 呢

**Comment by fankes** [comment]
`1.2.1` 版本已发布
