### ISSUE TITLE
手动设置appClassLoader 不生效

### ISSUE THREAD

**Issue by Xiaolangs** [HighCapable/YukiHookAPI#81]
Hook App Application 获取app classloader 后设置appclassloader 为获取的，当前hook下正常，通过loadhooker其他hook方法下的appclassloader不正确

**Comment by fankes** [comment]
请提供操作步骤的示例代码，已经打印每个 classloader 的完整日志

**Comment by Xiaolangs** [comment]
获取Classloader的Hooker
`object StartHooker : YukiBaseHooker() {
    override fun onHook() {
        "com.tencent.tinker.loader.app.TinkerApplication".toClass()
            .method {
                name("attachBaseContext")
                param(ContextClass)
            }.hook {
                after {
                    LogKTX.e(javaClass.name,"手动设置前的appClassloader",appClassLoader)
                    appClassLoader =
                        instance.current().superClass().method { name("getClassLoader") }
                            .invoke<ClassLoader>()
                    LogKTX.e(javaClass.name,"手动设置后的appClassloader",appClassLoader)
                    loadHooker(ChatUIHooker)
                }
            }
    }
}`
另一个Hooker
`object ChatUIHooker : YukiBaseHooker() {
    override fun onHook() {
        LogKTX.e(javaClass.name,"另一个Hooker下的appclassloader",appClassLoader)
        "com.tencent.mm.pluginsdk.ui.chat.d".toClass().method {
            name("getView")
            param(Int::class.java, View::class.java, ViewGroup::class.java)
        }.hook {
            after {
                LogKTX.e(javaClass.name, "HOOK到----getView")
            }
        }
    }
}`
![WX20240803-001153@2x](https://github.com/user-attachments/assets/f1c78bb8-71f9-4243-ba80-d5a397704aa8)

**Comment by fankes** [comment]
这两个 hooker 之间是怎么组合起来的

**Comment by Xiaolangs** [comment]
> 这两个 hooker 之间是怎么组合起来的

获取Classloader的Hooker hook -> after 方法里

**Comment by fankes** [comment]
appClassLoader 设计的是每个 Hooker 独立的，一个 PackageParam 持有一个独立的空间，你需要在每个 Hooker 里面都设置一次

**Comment by Xiaolangs** [comment]
> appClassLoader 设计的是每个 Hooker 独立的，一个 PackageParam 持有一个独立的空间，你需要在每个 Hooker 里面都设置一次

没办法弄成统一的吗？

**Comment by fankes** [comment]
> > appClassLoader 设计的是每个 Hooker 独立的，一个 PackageParam 持有一个独立的空间，你需要在每个 Hooker 里面都设置一次
> 
> 没办法弄成统一的吗？

可是你 loadHooker 无论是否为静态，都相当于创建了一个新的对象呀，肯定不可能持有上一个对象中的内容，你可以看看这个变量是怎么实现的，默认情况下会获取环境提供的 classloader，这块设计的时候就是这样决定的，如果你觉得繁琐，你可以写一个扩展函数在创建新 Hooker 时自动设置你自定义的 classloader 就可以了

**Comment by fankes** [comment]
这个问题将不作为 bug 进行修复，如有其它问题，可以继续在下方回复。
