### ISSUE TITLE
关于SharedPreferences读取问题

### ISSUE THREAD

**Issue by ucxl** [HighCapable/YukiHookAPI#88]
我在模块应用里自定义了一个SharedPreferences
context.getSharedPreferences("conf", Context.MODE_WORLD_READABLE);
然后我在hook用prefs("conf").get(PrefsData("test", false))读取不到变化的值，不知道为什么

如果在AndroidManifest.xml加上下面的就可以读取
meta-data android:name="xposedsharedprefs" android:value="true"

**Comment by fankes** [comment]
https://highcapable.github.io/YukiHookAPI/zh-cn/api/special-features/xposed-storage
https://highcapable.github.io/YukiHookAPI/zh-cn/api/public/com/highcapable/yukihookapi/hook/xposed/prefs/YukiHookPrefsBridge

请阅读文档。
