### ISSUE TITLE
使用支持安卓15的Lspatch 内置模块导致输入法高度获取异常和actionbar隐藏失效

### ISSUE THREAD

**Issue by Xiaolangs** [HighCapable/YukiHookAPI#89]
![WechatIMG625](https://github.com/user-attachments/assets/3c6a8ef0-8fed-407e-a964-271a4bdb06d0)
![WechatIMG626](https://github.com/user-attachments/assets/2f490108-0c88-4dbb-9c7b-b2fc966fc7ea)

如上图所示经过查找最终定位到registerModuleAppActivities导致的

**Comment by fankes** [comment]
模块资源注入不一定保证 100% 功能正常生效，如有需要请自行写布局，此问题不做修复，后期可能会更换注入方案

**Comment by Xiaolangs** [comment]
> 模块资源注入不一定保证 100% 功能正常生效，如有需要请自行写布局，此问题不做修复，后期可能会更换注入方案

此问题应该不是注入资源导致的吧 是使用代理activity时才出现的问题

**Comment by Xiaolangs** [comment]
> 是的，代理可能会出现问题，但是同时会进行资源注入，所以不做修复，本来就是折衷方案

好的那什么时候会进行更新呢

**Comment by fankes** [comment]
这个不是优先可能会解决的问题，因为注入的方案本来就会存在问题，所以大概率无法修复

**Comment by fankes** [comment]
而且看起来可能是你代理的 activity 样式有问题，建议换一个标准 compat 主题的 activity 重新尝试注入

**Comment by Xiaolangs** [comment]
> 而且看起来可能是你代理的 activity 样式有问题，建议换一个标准 compat 主题的 activity 重新尝试注入

谢谢，正在进行尝试更换替换，之前使用原版lsp是正常的，这是使用进行二改适配后的lsp才出现的问题
