### ISSUE TITLE
`isModuleActive` reporting wrong status

### ISSUE THREAD

**Issue by salvogiangri** [HighCapable/YukiHookAPI#95]
On Android 15 (One UI 7 beta) running latest [JingMatrix's LSPosed](https://github.com/JingMatrix/LSPosed) fork release, the API reports that the module is disabled while it is actually enabled and working.

<img loading="lazy" src="https://github.com/user-attachments/assets/a991872e-10b2-4e68-adca-b4bfb384a703" width="30%"/><br>

https://github.com/salvogiangri/KnoxPatch/blob/093e99b12e6f7249399b538b508da68dc4a07b1a/app/src/main/java/io/mesalabs/knoxpatch/ui/activity/InfoActivity.kt#L159-L189

[LSPosed_2024-12-05T16_05_45.174116.zip](https://github.com/user-attachments/files/18040617/LSPosed_2024-12-05T16_05_45.174116.zip)

**Comment by fankes** [comment]
This is a LSPosed databases bug, not API. Please use official LSPosed or LSPosed IT (Internal Test) version to report bug :)
